// Arxiu generat automaticament per ActualitzarLogos.bat 
const llistaSponsors = [ 
    "ARCÍS.png", 
    "BPM.jpg", 
    "CALTORI.png", 
    "COMAS.png", 
    "CONSORCI.png", 
    "CORASERRA.jpg", 
    "CORRAL.png", 
    "COSAFEL.png", 
    "FERBIKES.png", 
    "FORJACAPELLAS.png", 
    "HORTPUIG.png", 
    "LIBEXCRONOS.png", 
    "LLOBARTERA.png", 
    "MARTABOIXADER.png", 
    "SALERSVINYES.PNG", 
    "TEXPUHER.png", 
    "TOTIMES.png", 
    "VITAL.png", 
]; 
